pub mod app;
pub mod claude;
// FUTURE: #48 — Codex provider; re-enable when multi-vendor registry is implemented
// pub mod codex;
pub mod doctor;
pub mod driver;
pub mod error;
pub mod execution;
pub mod feature_start;
pub mod github;
pub mod headless;
pub mod headless_persist;
pub mod headless_sm;
pub mod headless_sm_driver;
pub mod init;
pub mod interpreter_scheduler;
pub mod keys;
pub mod operator_surface;
pub mod pinned_prompt;
pub mod policy;
pub mod pr_checklist;
pub mod report;
pub mod runtime;
pub mod signal;
pub mod sm_audit;
pub mod state;
pub mod telemetry;
pub mod template;
mod template_assets;
pub mod workflows;
